language: ruby
rvm: 
  - 2.1.5
script: 
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site/ -- disable-external --check-favicon --check-html --only-4xx
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
