language: ruby
rvm: 
  - 2.1.7
script: 
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --check_html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
